//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_TRAINING
    {
        public string REQUEST_NAME { get; set; }
        public string SKILL { get; set; }
        public System.DateTime START_D { get; set; }
        public System.DateTime END_D { get; set; }
    }
}
